services:
    kafkaServer:
        image: apache/kafka:latest
        hostname: kafkaServer
        container_name: kafkaServer
        ports:
        - '9092:9092'
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://kafkaServer:9092,PLAINTEXT://kafkaServer:19092'
            KAFKA_PROCESS_ROLES: 'broker,controller'
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafkaServer:29093'
            KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'  
    topics:
        image: apache/kafka:latest
        command: >
            bash -c "
            /opt/kafka/bin/kafka-topics.sh --create --topic babel-input --bootstrap-server kafkaServer:9092
            && /opt/kafka/bin/kafka-topics.sh --create --topic babel-output --bootstrap-server kafkaServer:9092"
        depends_on:
        - kafkaServer
    fluentd:
        depends_on:
            topics:
                condition: service_completed_successfully
        image: tap:fluentd
        build:
            context: fluentd
        ports:
            - "9880:9880"
        command: "-c /fluentd/etc/fluentd.conf"
        volumes:
            - ./fluentd/fluentd.conf:/fluentd/etc/fluentd.conf:ro
    translator:
        image: tap:translator
        build:
            context: translator
        command: "java -cp /app/app.jar tap.Translator"
    logstash:
        depends_on:
            - topics
        image: docker.elastic.co/logstash/logstash:8.15.3
        environment:
            XPACK_MONITORING_ENABLED: "false"
        volumes:
            - ./logstash/logs/:/usr/share/logstash/pipeline/logs/:rw
            - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro

